### ISSUE TITLE
hotkey

### ISSUE THREAD

**Issue by nirilan** [c-yan/open-all-urls-in-the-clipboard#1]
Hi,

Can you add an option to assign a keyboard shortcut to the add-on(for example CTRL+ALT+V will open all URLs in the clipboard)?

**Comment by c-yan** [comment]
Short answer: I will consider implementing it.

Long answer: Setting a shortcut key statically is technically very easy. However, I think that it is better for users to be able to customize the shortcut keys themselves. It seems that it became possible with Firefox 60(https://bugzilla.mozilla.org/show_bug.cgi?id=1421811). However, it takes a while because I never implemented setting screen of WebExtensions.

**Comment by c-yan** [comment]
This is status update! I investigated the option page of the add-on and setting preservation. And I am asking the community about what I can not understand.

**Comment by c-yan** [comment]
@nirilan I've released a new version. please check it!
